name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust the Python version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variables
      - name: Set environment variables
        run: echo "APP_PORT=5000" >> "$GITHUB_ENV"

      # Step 5: Run the Flask app in the background
      - name: Run Flask app
        run: |
          nohup python app.py &
        env:
          FLASK_ENV: testing  # Set any necessary environment variables
          APP_PORT: ${{ env.APP_PORT }}

      # Step 6: Wait for the server to start
      - name: Wait for server to start
        run: sleep 45

      # Step 7: Check /health-check endpoint
      - name: Test /health-check endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ env.APP_PORT }}/health-check)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Health check failed with status code $STATUS_CODE"
            exit 1
          fi
          echo "Health check passed with status code $STATUS_CODE"